services:
  surechembl:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: surechembl_container

    volumes:
      # - ../data:/app/data
      - ..:/app

    environment:
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python

    tty: true